### ISSUE TITLE
Memory Leak due to strong reference to InfiniteCollectionViewDelegate

### ISSUE THREAD

**Issue by si-lang** [arnauddorgans/InfiniteLayout#1]
Hey!
Thank you for your nice infinite layout implementation. I found a possible memory leak in your code. The line:
`@IBOutlet open var infiniteDelegate: InfiniteCollectionViewDelegate?`
should actually read:
`@IBOutlet weak open var infiniteDelegate: InfiniteCollectionViewDelegate?`

Otherwise you will have a strong retain cycle if the view controller presenting the collection view is also the delegate of the collection view.

I don't think that this issue is also the case for your overrides of the standard UICollectionView's delegate and data source, because they are defined as weak references by Apple and you don't override this weak with your overrides. BUT: For convenience reasons I would also recommend you to also add weak to those properties (so that everyone knows ;) ).
Apart from that: Keep it up!

Best Regards!

**Comment by arnauddorgans** [comment]
Hi !
Indeed i didn't see that
I've made the fixes thanks to you
Thx for your feedback !
