### ISSUE TITLE
Unable to import Rx bindings through Swift Package Manager

### ISSUE THREAD

**Issue by cdann-leafly** [arnauddorgans/InfiniteLayout#17]
The InfiniteLayout Rx bindings, which are in a separate sub-spec for Cocoapods, were left out entirely of the SPM package definition. 

This makes it not possible to use InfiniteLayout with Rx bindings when trying to manage dependencies with SPM.

I've updated the package manifest to define a separate library for the Rx bindings, which can optionally be included as a dependency. This should leave the existing package (defined without Rx bindings) unaffected and mirrors the setup for Cocoapods with 2 different libraries.

I've opened a pull request with these changes here: https://github.com/arnauddorgans/InfiniteLayout/pull/16

Please have a look when you are able, and please let me know if there are any issues or changes you would require before merging.

Thanks!
-Chris

**Comment by arnauddorgans** [comment]
Hi ! 
Thanks a lot for your PR ! I do not have a lot of time recently to maintain this project.

**Comment by cdann-leafly** [comment]
No problem! Happy to contribute. Thank you for sharing your work!
