### ISSUE TITLE
InfiniteCollectionViewDelegate is not working

### ISSUE THREAD

**Issue by laurentNoudohounsi** [arnauddorgans/InfiniteLayout#29]
Hi! Thanks for the great library.
It works very well and easy to use. However it seems that the `InfiniteCollectionViewDelegate` isn't working. In the exemple the picker view never displayes the selected item. Also adding a `InfiniteCollectionViewDelegate` to the `BaseCollectionViewController` doesn't work too...

In the file `InfiniteCollectionView.swift` the current function seems to have an issue:

```swift
func updateLayoutIfNeeded() {
        self.loopCollectionViewIfNeeded()
        self.centerCollectionViewIfNeeded()
        
        let preferredVisibleIndexPath = infiniteLayout.preferredVisibleLayoutAttributes()?.indexPath
        if self.centeredIndexPath != preferredVisibleIndexPath {
            let previousCenteredIndexPath = self.centeredIndexPath
            self.centeredIndexPath = preferredVisibleIndexPath
            self.infiniteDelegate?.infiniteCollectionView?(self, didChangeCenteredIndexPath: previousCenteredIndexPath, to: self.centeredIndexPath)
        }
}
```
Where `let preferredVisibleIndexPath = infiniteLayout.preferredVisibleLayoutAttributes()?.indexPath` is always nil. Hence the line that use the delegate is never reached.

Do you have any insight regarding this issue @arnauddorgans ?

**Comment by StuGisburne** [comment]
Yep...same issue here. @laurentNoudohounsi did you use a fix?

**Comment by l16i** [comment]
@StuGisburne Unfortunately no. I didn't spend more time since the project I was worked on has been aborted.

**Comment by StuGisburne** [comment]
Ahh...Use the delegate function below instead  @laurentNoudohounsi

func infiniteCollectionView(_ infiniteCollectionView: InfiniteCollectionView, didChangeCenteredIndexPath from: IndexPath?, to: IndexPath?) {

}

**Comment by l16i** [comment]
@StuGisburne Thank you for the insight. It would be usefull for the next projects :)
