### ISSUE TITLE
Disable infinite scroll when number of cells is 1

### ISSUE THREAD

**Issue by loksurya** [arnauddorgans/InfiniteLayout#5]
I am not able to disable infinite scroll when number of items are 1. Help

**Comment by arnauddorgans** [comment]
Hi ! 
Thx for your feedback, you can now update InfiniteLayout to 0.2.3.4, there is a new public property called "isEnabled", you can easily add a condition just before reloading data in your collectionView.

Exemple:

```swift
self.collectionView.infiniteLayout.isEnabled = self.items.count > 1
```

Tell me if it's okay for you !

**Comment by loksurya** [comment]
Thanks, @arnauddorgans
it is working now.
