### ISSUE TITLE
How to access UIScrollViewDelegate of an InfiniteCollectionView

### ISSUE THREAD

**Issue by cleverClosure** [arnauddorgans/InfiniteLayout#6]
Hello. I'm having this problem, the UIScrollViewDelegate methods I implemented, are not being called. Is there a way to make it work?

**Comment by arnauddorgans** [comment]
Hello :) 
Can you copy past your code please ?

**Comment by cleverClosure** [comment]
Sure.

`
import UIKit
import CoreLocation
import InfiniteLayout

class MapVC: UIViewController {

    @IBOutlet weak var cvContainers: InfiniteCollectionView!
    
    var minimumLineSpacing: CGFloat = 7
    
    var cellSize: CGSize {
        return CGSize(width: 274, height: 85)
    }
    
    lazy var collectionViewLayout: InfiniteLayout = {
        let layout = InfiniteLayout()
        layout.scrollDirection = .horizontal
        layout.minimumLineSpacing = minimumLineSpacing
        layout.itemSize = cellSize
        layout.sectionInset = sectionInset
        return layout
    }()
    
    var sectionInset: UIEdgeInsets {
        let widthDiff = view.frame.width - (cellSize.width + minimumLineSpacing * 2)
        let padding = widthDiff / 2
        return UIEdgeInsets(top: 0, left: padding, bottom: 0, right: padding)
    }
    
    lazy var alertPresenter: AlertPresenter = {
        return AlertPresenter(viewController: self)
    }()
    
    lazy var locationManager: CLLocationManager = {
        let manager = CLLocationManager()
        manager.delegate = self
        manager.desiredAccuracy = kCLLocationAccuracyNearestTenMeters
        manager.distanceFilter = 50
        manager.startUpdatingLocation()
        return manager
    }()
    
    var data: [Container] = [] {
        didSet {
            cvContainers.reloadData()
        }
    }
    
    //MARK: Life cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        cvContainers.collectionViewLayout = collectionViewLayout
        cvContainers.showsHorizontalScrollIndicator = false
        cvContainers.delegate = self
        cvContainers.dataSource = self
        setupUI()
    }
    
    //MARK: Setup UI
    private func setupUI() {
        // do something
    }
    
}

extension MapVC: UIScrollViewDelegate {
    
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        // do something
    }
    
    func scrollViewWillEndDragging(_ scrollView: UIScrollView, withVelocity velocity: CGPoint, targetContentOffset: UnsafeMutablePointer<CGPoint>) {
        
        // do something    
        
    }
}

extension MapVC: UICollectionViewDataSource {
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 5
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "MapContainerCell", for: indexPath)
        
        return cell
    }
}

extension MapVC: UICollectionViewDelegateFlowLayout, UICollectionViewDelegate {
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        return cellSize
    }
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        collectionView.scrollToItem(at: indexPath, at: .centeredHorizontally, animated: true)
    }
    
}

extension MapVC: InfiniteCollectionViewDelegate {
    
    func infiniteCollectionView(_ infiniteCollectionView: InfiniteCollectionView, didChangeCenteredIndexPath centeredIndexPath: IndexPath?) {
        guard let indexPath = centeredIndexPath else {
            return
        }
        let idx = self.cvContainers.indexPath(from: indexPath).row
        
    }
}
`

**Comment by cleverClosure** [comment]
What's not being called is scrollViewWillEndDragging. 

scrollViewDidScroll on the other hand does get called

**Comment by arnauddorgans** [comment]
Fixed in 0.3 👍 
Please pod update
Thanks for your feedback

**Comment by cleverClosure** [comment]
is it really fixed though? :)

**Comment by arnauddorgans** [comment]
tested on project example :) 

add the following code and you will see the log
```
  func scrollViewWillEndDragging(_ scrollView: UIScrollView, withVelocity velocity: CGPoint, targetContentOffset: UnsafeMutablePointer<CGPoint>) {
    print("scrollViewWillEndDragging")
  }
```
